server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hazardous?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: false  #清除缓存

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
#富文本编辑器
minio:
  bucketName: uploads # 存储桶名字
  endpoint: 127.0.0.1 #桶所在节点ip
  port: 9000      # web管理服务访问端口
  secure: false  #false为http   true为 https
  accessKey: minioadmin #登录账号
  secretKey: minioadmin #密码
pic:
  prefix: http://localhost:80/uploads/ #图片访问路径前缀
#shiro配置
shiro:
  loginUrl: /notlogin.html #未认证的用户跳转登录到页面请求
  successUrl: /index.html #认证成功跳转的页面
  unauthorizedUrl: /notauth.html #无权访问的页面
